import { Component, OnInit, computed, signal } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ApiService } from '../../core/services/api.service';
import { Modlist } from '../../shared/models/mod.model';
import { trigger, transition, style, animate, query, stagger } from '@angular/animations';

@Component({
  selector: 'app-modlist',
  standalone: true,
  imports: [],
  animations: [
    trigger('fadeUp', [
      transition(':enter', [
        style({ opacity: 0, transform: 'translateY(12px)' }),
        animate('350ms cubic-bezier(0.16, 1, 0.3, 1)', style({ opacity: 1, transform: 'translateY(0)' })),
      ]),
    ]),
    trigger('staggerMods', [
      transition(':enter', [
        query('.mod-card', [
          style({ opacity: 0, transform: 'translateY(8px)' }),
          stagger(40, [
            animate('300ms cubic-bezier(0.16, 1, 0.3, 1)', style({ opacity: 1, transform: 'translateY(0)' })),
          ]),
        ], { optional: true }),
      ]),
    ]),
  ],
  template: `
    <div class="modlist-page">
      @if (loading()) {
        <div class="loading">
          <span class="load-spinner"></span>
          <p>Loading loadout...</p>
        </div>
      } @else if (modlist()) {
        <div class="modlist-header" @fadeUp>
          <div>
            <span class="page-label">Your Loadout</span>
            <h1>{{ coreMods().length }} Mods @if (patchMods().length) { + {{ patchMods().length }} Patches }</h1>
            @if (modlist()!.used_fallback) {
              <p class="subtitle fallback-label">Curated fallback list (AI generation failed)</p>
            } @else if (modlist()!.llm_provider) {
              <p class="subtitle">Generated by {{ modlist()!.llm_provider }}</p>
            }
          </div>
          <div class="header-actions">
            <button class="btn-back" (click)="goToSetup()">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M19 12H5M12 19l-7-7 7-7"/>
              </svg>
              New Loadout
            </button>
            <button class="btn-copy" (click)="copyUrl()">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <rect x="9" y="9" width="13" height="13" rx="2"/>
                <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/>
              </svg>
              {{ copied() ? 'Copied!' : 'Copy URL' }}
            </button>
          </div>
        </div>

        <!-- MO2 integration banner -->
        <div class="mo2-banner" @fadeUp>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
            <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3"/>
          </svg>
          <div>
            <strong>Install with Mod Organizer 2</strong>
            <p>Use the ModdersOmni plugin for MO2 to download and install this modlist. Paste this page's URL into the plugin's import dialog.</p>
          </div>
        </div>

        <div class="mod-list" @staggerMods>
          @for (entry of modlist()!.entries; track $index) {
            <div class="mod-card" [class.patch-card]="entry.is_patch">
              <div class="mod-order" [class.patch-order]="entry.is_patch">
                @if (entry.is_patch) {
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
                    <path d="M12 5v14M5 12h14"/>
                  </svg>
                } @else {
                  {{ entry.load_order || $index + 1 }}
                }
              </div>
              <div class="mod-info">
                <div class="mod-header">
                  @if (entry.is_patch) {
                    <span class="patch-badge">PATCH</span>
                  }
                  <h3>{{ entry.name }}</h3>
                  @if (entry.author) {
                    <span class="mod-author">by {{ entry.author }}</span>
                  }
                </div>
                @if (entry.is_patch && entry.patches_mods?.length) {
                  <p class="patches-subtitle">Patches: {{ entry.patches_mods!.join(' + ') }}</p>
                }
                @if (entry.summary) {
                  <p class="mod-summary">{{ entry.summary }}</p>
                }
                @if (entry.reason) {
                  <p class="mod-reason">{{ entry.reason }}</p>
                }
                @if (entry.compatibility_notes) {
                  <p class="compat-note">{{ entry.compatibility_notes }}</p>
                }
              </div>
              @if (entry.nexus_mod_id && modlist()!.game_domain) {
                <a class="nexus-link"
                   [href]="'https://www.nexusmods.com/' + modlist()!.game_domain + '/mods/' + entry.nexus_mod_id"
                   target="_blank" rel="noopener">
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6M15 3h6v6M10 14L21 3"/>
                  </svg>
                </a>
              }
            </div>
          }
        </div>

        @if (modlist()!.user_knowledge_flags?.length) {
          <div class="knowledge-section" @fadeUp>
            <h2 class="section-title">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/>
                <line x1="12" y1="9" x2="12" y2="13"/>
                <line x1="12" y1="17" x2="12.01" y2="17"/>
              </svg>
              Compatibility Notes
            </h2>
            <p class="section-desc">These mod pairs may have compatibility issues. No patches were found on Nexus.</p>
            @for (flag of modlist()!.user_knowledge_flags; track $index) {
              <div class="knowledge-flag" [class.flag-critical]="flag.severity === 'critical'">
                <div class="flag-header">
                  <span class="flag-severity" [class]="'severity-' + flag.severity">{{ flag.severity }}</span>
                  <span class="flag-mods">{{ flag.mod_a }} + {{ flag.mod_b }}</span>
                </div>
                <p class="flag-issue">{{ flag.issue }}</p>
              </div>
            }
          </div>
        }

        @if (modlist()!.entries.length === 0) {
          <div class="empty-state" @fadeUp>
            <div class="empty-icon">
              <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                <path d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"/>
              </svg>
            </div>
            <p>No mods in this loadout yet.</p>
            <button class="btn-primary" (click)="goToSetup()">Forge New Loadout</button>
          </div>
        }
      } @else {
        <div class="empty-state" @fadeUp>
          <div class="empty-icon">
            <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
              <circle cx="12" cy="12" r="10"/>
              <path d="M15 9l-6 6M9 9l6 6"/>
            </svg>
          </div>
          <p>Loadout not found.</p>
          <button class="btn-primary" (click)="goToSetup()">Forge New Loadout</button>
        </div>
      }
    </div>
  `,
  styles: [`
    .modlist-page {
      max-width: 800px;
      margin: 0 auto;
      padding: 2.5rem 2rem;
    }

    /* Loading */
    .loading {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 6rem 2rem;
      gap: 1rem;
      color: var(--color-text-muted);
      font-size: 0.875rem;
    }
    .load-spinner {
      width: 28px;
      height: 28px;
      border: 2px solid var(--color-border);
      border-top-color: var(--color-gold);
      border-radius: 50%;
      animation: spin 0.6s linear infinite;
    }
    @keyframes spin { to { transform: rotate(360deg); } }

    /* Header */
    .modlist-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 1.5rem;
    }
    .page-label {
      display: inline-block;
      font-size: 0.6875rem;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.1em;
      color: var(--color-gold);
      margin-bottom: 0.375rem;
    }
    h1 {
      font-family: var(--font-display);
      font-size: 1.75rem;
      font-weight: 500;
      letter-spacing: -0.01em;
      margin: 0 0 0.25rem;
    }
    .subtitle {
      font-size: 0.8125rem;
      color: var(--color-text-muted);
      margin: 0;
    }
    .fallback-label {
      color: #e8a735;
    }
    .header-actions {
      display: flex;
      align-items: center;
      gap: 0.75rem;
    }
    .btn-back {
      display: inline-flex;
      align-items: center;
      gap: 0.375rem;
      background: none;
      border: none;
      color: var(--color-text-muted);
      font-size: 0.8125rem;
      font-weight: 500;
      padding: 0.5rem 0;
      cursor: pointer;
      transition: color 0.15s;
    }
    .btn-back:hover { color: var(--color-text); }
    .btn-copy {
      display: inline-flex;
      align-items: center;
      gap: 0.375rem;
      background: var(--color-bg-elevated);
      border: 1px solid var(--color-border);
      color: var(--color-text-muted);
      padding: 0.5rem 1rem;
      border-radius: 8px;
      font-size: 0.8125rem;
      font-weight: 500;
      cursor: pointer;
      transition: color 0.15s, border-color 0.15s;
    }
    .btn-copy:hover {
      color: var(--color-text);
      border-color: var(--color-border-hover);
    }
    .btn-primary {
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      background: var(--color-gold);
      color: #0D0D0F;
      padding: 0.625rem 1.5rem;
      border-radius: 8px;
      font-weight: 600;
      border: none;
      cursor: pointer;
      font-size: 0.875rem;
      transition: background 0.2s, box-shadow 0.3s;
    }
    .btn-primary:hover {
      background: var(--color-gold-hover);
      box-shadow: var(--shadow-gold);
      transform: translateY(-1px);
    }
    .btn-primary:active { transform: translateY(0); }

    /* MO2 banner */
    .mo2-banner {
      display: flex;
      gap: 0.875rem;
      padding: 1rem 1.25rem;
      background: rgba(123, 164, 192, 0.06);
      border: 1px solid rgba(123, 164, 192, 0.15);
      border-radius: var(--radius-md);
      margin-bottom: 1.5rem;
      color: var(--color-blue, #7ba4c0);
    }
    .mo2-banner svg { flex-shrink: 0; margin-top: 2px; }
    .mo2-banner strong {
      display: block;
      font-size: 0.8125rem;
      color: var(--color-text);
      margin-bottom: 0.25rem;
    }
    .mo2-banner p {
      font-size: 0.8125rem;
      color: var(--color-text-muted);
      margin: 0;
      line-height: 1.45;
    }

    /* Mod list */
    .mod-list {
      display: flex;
      flex-direction: column;
      gap: 0.5rem;
    }
    .mod-card {
      background: var(--color-bg-card);
      border: 1px solid var(--color-border);
      border-left: 3px solid var(--color-gold);
      border-radius: var(--radius-md);
      padding: 1rem 1.25rem;
      display: flex;
      align-items: flex-start;
      gap: 1rem;
      transition: border-color 0.2s, box-shadow 0.25s, transform 0.2s var(--ease-out);
    }
    .mod-card:hover {
      border-color: rgba(196, 165, 90, 0.2);
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2), 0 0 0 1px rgba(196, 165, 90, 0.06);
      transform: translateX(2px);
    }

    /* Patch card variant */
    .mod-card.patch-card {
      border-left-color: var(--color-blue, #7ba4c0);
      background: rgba(123, 164, 192, 0.03);
    }
    .mod-card.patch-card:hover {
      border-color: rgba(123, 164, 192, 0.2);
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2), 0 0 0 1px rgba(123, 164, 192, 0.06);
    }

    .mod-order {
      min-width: 28px;
      height: 28px;
      background: rgba(192, 160, 96, 0.12);
      border: 1px solid rgba(192, 160, 96, 0.2);
      border-radius: 6px;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 0.75rem;
      font-weight: 600;
      color: var(--color-gold);
      flex-shrink: 0;
      margin-top: 2px;
    }
    .mod-order.patch-order {
      background: rgba(123, 164, 192, 0.12);
      border-color: rgba(123, 164, 192, 0.2);
      color: var(--color-blue, #7ba4c0);
    }

    .mod-info { flex: 1; min-width: 0; }
    .mod-header {
      display: flex;
      align-items: baseline;
      gap: 0.5rem;
      flex-wrap: wrap;
    }
    .mod-header h3 {
      font-size: 0.9375rem;
      font-weight: 600;
      margin: 0;
    }
    .mod-author {
      font-size: 0.75rem;
      color: var(--color-text-dim);
    }
    .patch-badge {
      font-size: 0.625rem;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.06em;
      padding: 0.125rem 0.4rem;
      border-radius: 4px;
      background: rgba(123, 164, 192, 0.15);
      color: var(--color-blue, #7ba4c0);
      border: 1px solid rgba(123, 164, 192, 0.25);
    }
    .patches-subtitle {
      font-size: 0.75rem;
      color: var(--color-blue, #7ba4c0);
      margin: 0.25rem 0 0;
      opacity: 0.85;
    }
    .mod-summary {
      font-size: 0.8125rem;
      color: var(--color-text-muted);
      margin: 0.375rem 0 0;
      line-height: 1.45;
    }
    .mod-reason {
      font-size: 0.75rem;
      color: var(--color-gold);
      margin: 0.25rem 0 0;
      font-style: italic;
      opacity: 0.8;
    }
    .compat-note {
      font-size: 0.75rem;
      color: var(--color-warning, #eab308);
      margin: 0.375rem 0 0;
      padding: 0.25rem 0.5rem;
      background: rgba(234, 179, 8, 0.06);
      border-left: 2px solid rgba(234, 179, 8, 0.3);
      border-radius: 0 4px 4px 0;
    }

    /* Nexus link */
    .nexus-link {
      flex-shrink: 0;
      width: 32px;
      height: 32px;
      display: flex;
      align-items: center;
      justify-content: center;
      border-radius: 6px;
      color: var(--color-text-dim);
      transition: color 0.15s, background 0.15s;
      margin-top: 2px;
    }
    .nexus-link:hover {
      color: var(--color-gold);
      background: rgba(196, 165, 90, 0.08);
    }

    /* Knowledge flags section */
    .knowledge-section {
      margin-top: 2rem;
      padding-top: 1.5rem;
      border-top: 1px solid var(--color-border);
    }
    .section-title {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      font-size: 1rem;
      font-weight: 600;
      margin: 0 0 0.375rem;
      color: var(--color-warning, #eab308);
    }
    .section-desc {
      font-size: 0.8125rem;
      color: var(--color-text-muted);
      margin: 0 0 1rem;
    }
    .knowledge-flag {
      background: rgba(234, 179, 8, 0.04);
      border: 1px solid rgba(234, 179, 8, 0.15);
      border-left: 3px solid rgba(234, 179, 8, 0.4);
      border-radius: var(--radius-md);
      padding: 0.75rem 1rem;
      margin-bottom: 0.5rem;
    }
    .knowledge-flag.flag-critical {
      background: rgba(239, 68, 68, 0.04);
      border-color: rgba(239, 68, 68, 0.15);
      border-left-color: rgba(239, 68, 68, 0.5);
    }
    .flag-header {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      margin-bottom: 0.25rem;
    }
    .flag-severity {
      font-size: 0.625rem;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.06em;
      padding: 0.1rem 0.375rem;
      border-radius: 4px;
    }
    .severity-warning {
      background: rgba(234, 179, 8, 0.15);
      color: var(--color-warning, #eab308);
    }
    .severity-critical {
      background: rgba(239, 68, 68, 0.15);
      color: var(--color-error, #ef4444);
    }
    .flag-mods {
      font-size: 0.8125rem;
      font-weight: 600;
    }
    .flag-issue {
      font-size: 0.8125rem;
      color: var(--color-text-muted);
      margin: 0;
      line-height: 1.45;
    }

    /* Empty state */
    .empty-state {
      text-align: center;
      padding: 5rem 2rem;
      color: var(--color-text-muted);
    }
    .empty-icon {
      width: 56px;
      height: 56px;
      border-radius: 14px;
      background: rgba(255, 255, 255, 0.04);
      border: 1px solid var(--color-border);
      display: flex;
      align-items: center;
      justify-content: center;
      margin: 0 auto 1.25rem;
      color: var(--color-text-dim);
    }
    .empty-state p {
      margin-bottom: 1.25rem;
      font-size: 0.9375rem;
    }
  `],
})
export class ModlistComponent implements OnInit {
  modlist = signal<Modlist | null>(null);
  loading = signal(true);
  copied = signal(false);

  coreMods = computed(() => {
    const ml = this.modlist();
    return ml ? ml.entries.filter(e => !e.is_patch) : [];
  });

  patchMods = computed(() => {
    const ml = this.modlist();
    return ml ? ml.entries.filter(e => e.is_patch) : [];
  });

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private api: ApiService,
  ) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.api.getModlist(id).subscribe({
        next: (modlist) => {
          this.modlist.set(modlist);
          this.loading.set(false);
        },
        error: () => {
          this.loading.set(false);
        },
      });
    } else {
      this.loading.set(false);
    }
  }

  copyUrl(): void {
    navigator.clipboard.writeText(window.location.href).then(() => {
      this.copied.set(true);
      setTimeout(() => this.copied.set(false), 2000);
    });
  }

  goToSetup(): void {
    this.router.navigate(['/setup']);
  }
}
